import "./globals.css";
import type { Metadata } from "next";
import { Bricolage_Grotesque } from "next/font/google";
import Script from "next/script";
import { ThemeProvider } from "next-themes";
import NextTopLoader from "nextjs-toploader";
import SessionProviderComp from "@/components/nextauth/SessionProvider";
import { Providers } from "./providers";
import { Suspense } from "react";
import { Analytics } from "@vercel/analytics/react";

const font = Bricolage_Grotesque({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Elite Property - Islamabad DHA",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  session,
}: Readonly<{
  children: React.ReactNode;
  session: unknown;
}>) {
  return (
    <html lang="en">
      <head>
        {/* Meta Pixel Code */}
        <Script id="facebook-pixel" strategy="afterInteractive">
          {`
            !function(f,b,e,v,n,t,s)
            {if(f.fbq)return;n=f.fbq=function(){n.callMethod?
            n.callMethod.apply(n,arguments):n.queue.push(arguments)};
            if(!f._fbq)f._fbq=n;n.push=n;n.loaded=!0;n.version='2.0';
            n.queue=[];t=b.createElement(e);t.async=!0;
            t.src=v;s=b.getElementsByTagName(e)[0];
            s.parentNode.insertBefore(t,s)}(window, document,'script',
            'https://connect.facebook.net/en_US/fbevents.js');
            fbq('init', '1763559634157665');
            fbq('track', 'PageView');
          `}
        </Script>

        {/* Google tag (gtag.js) - AW-17506316720 */}
        <Script
          src="https://www.googletagmanager.com/gtag/js?id=AW-17506316720"
          strategy="afterInteractive"
          async
        />
        <Script id="gtag" strategy="afterInteractive">
          {`
            window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);} 
            gtag('js', new Date());

            gtag('config', 'AW-17506316720');
          `}
        </Script>


        <noscript>
          <img
            height="1"
            width="1"
            style={{ display: "none" }}
            src="https://www.facebook.com/tr?id=1763559634157665&ev=PageView&noscript=1"
            alt=""
          />
        </noscript>
      </head>

      <body className={`${font.className} bg-white dark:bg-black antialiased`}>
        <NextTopLoader color="#d8b648" showSpinner={false} />
        <SessionProviderComp session={session}>
          <ThemeProvider
            attribute="class"
            enableSystem={true}
            defaultTheme="light"
          >
            <Providers>
              <Suspense fallback={null}>{children}</Suspense>
            </Providers>
          </ThemeProvider>
        </SessionProviderComp>
        <Analytics />
      </body>
    </html>
  );
}
